# Generated by Django 2.2.4 on 2022-06-14 18:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='media_root/images/1.png', upload_to=core.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='media_root/images/1.png', upload_to=core.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=core.models.path_and_rename),
        ),
    ]
