# Generated by Django 2.2.4 on 2022-06-14 18:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220614_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(upload_to=core.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(upload_to=core.models.path_and_rename),
        ),
    ]
