# Generated by Django 4.0.2 on 2022-06-21 19:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=django_countries.fields.CountryField(default=None, max_length=100),
        ),
    ]
