# Generated by Django 4.0.2 on 2022-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_billingaddress_email_alter_billingaddress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
