# Generated by Django 4.0.2 on 2022-06-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_billingaddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rQty',
            field=models.IntegerField(default=0),
        ),
    ]
