# Generated by Django 4.0.2 on 2022-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_qty_item_rqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Number',
            field=models.IntegerField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='nickName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
