# Generated by Django 4.0.2 on 2022-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_orderitem_number_orderitem_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='M', max_length=50),
        ),
    ]
