# Generated by Django 4.0.2 on 2022-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Shippingfee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='saleTax',
            field=models.IntegerField(default=0),
        ),
    ]
