# Generated by Django 4.0.2 on 2022-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_shippingfee_order_saletax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addToHome',
            field=models.BooleanField(default=False),
        ),
    ]
