# Generated by Django 4.0.2 on 2022-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_item_addtohome'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mailSended',
            field=models.BooleanField(default=False),
        ),
    ]
