# Generated by Django 4.0.2 on 2022-06-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_mailsended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='nickName',
        ),
    ]
