# Generated by Django 4.0.2 on 2022-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_orderitem_number_remove_orderitem_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minamount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
