# Generated by Django 4.0.2 on 2022-06-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_coupon_minamount_alter_coupon_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minamount',
            new_name='min_amount',
        ),
    ]
