# Generated by Django 4.0.2 on 2022-06-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_shippingfee_item_saletax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Shippingfee',
            new_name='Shipping',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='saleTax',
            new_name='Tax',
        ),
    ]
