# Generated by Django 4.0.2 on 2022-06-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_shippingfee_item_shipping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Shipping',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Tax',
        ),
    ]
