# Generated by Django 4.0.2 on 2022-06-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_item_shipping_item_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Shipping',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='saleTax',
        ),
        migrations.AlterField(
            model_name='order',
            name='Shippingfee',
            field=models.IntegerField(default=25),
        ),
    ]
