# Generated by Django 4.0.2 on 2022-06-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_newsletter_subcribers_sendnewstosubcriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcribers',
            old_name='dat',
            new_name='date',
        ),
    ]
