# Generated by Django 4.0.2 on 2022-06-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_sendnewstosubcriber_newsletter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='caption1',
            new_name='caption1_en',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='caption2',
            new_name='caption2_en',
        ),
        migrations.AddField(
            model_name='slide',
            name='caption1_ro',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='slide',
            name='caption2_ro',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
