# Generated by Django 4.0.2 on 2022-06-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_slide_caption1_ro_remove_slide_caption2_ro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='caption1_en',
            new_name='caption1',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='caption2_en',
            new_name='caption2',
        ),
    ]
