# Generated by Django 4.0.2 on 2022-06-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_caption1_slide_caption1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='is_ae',
            field=models.BooleanField(default=True),
        ),
    ]
