# Generated by Django 4.0.2 on 2022-06-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_slide_is_ae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='caption1_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption1_ro',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption2_en',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='caption2_ro',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
    ]
