# Generated by Django 4.0.2 on 2022-06-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_slide_caption1_en_remove_slide_caption1_ro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='caption1_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='caption1_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='caption2_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='caption2_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, help_text='Size: 1920x570', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
